export const SIDE_ORDER = [
  {
    id: 1,
    category: 'SideOrder',
    name: 'Side of Pasta',
    description: 'Choice of pasta topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/pasta.webp',
    size1: 'Side portion',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 2,
    category: 'SideOrder',
    name: 'Side of Pasta & Meatball',
    description: 'Choice of pasta topped with marinara sauce, one jumbo meatball, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/meatball-pasta.webp',
    size1: 'Side portion',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
  {
    id: 3,
    category: 'SideOrder',
    name: 'Side of Pasta & Sausage',
    description: 'Choice of pasta topped with marinara sauce, one sausage link, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/sausage-pasta.webp',
    size1: 'Side portion',
    price1: 8.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: true
  },
 
  {
    id: 1,
    category: 'SideOrder',
    name: 'Side of Meatballs',
    description: 'Twin jumbo meatballs topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/meatballs.webp',
    size1: 'Two jumbo meatballs',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 2,
    category: 'SideOrder',
    name: 'Side of Sausage',
    description: 'Twin sweet Italian sausage links topped with marinara sauce, parmesan, & Italian herbs.',
    images: '/images/menu-items/side/sausage.webp',
    size1: 'Two links',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 3,
    category: 'SideOrder',
    name: 'Garlic Bread',
    description: 'Foot long Italian bread brushed with garlic herb butter & lightly toasted. Served with marinara.',
    images: '/images/menu-items/app/garlic-bread.webp',
    size1: '12 inch baguette',
    price1: 6.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 4,
    category: 'SideOrder',
    name: 'Fries',
    description: 'Tossed with salt, black pepper, garlic seasoning, oregano, & parsley.',
    images: '/images/menu-items/app/fries.webp',
    size1: 'Side of fries',
    price1: 5.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
 {
    id: 5,
    category: 'SideOrder',
    name: 'Ranch Dressing',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: '4oz portion',
    price1: 0.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 6,
    category: 'SideOrder',
    name: 'Blue Cheese Dressing',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: '4oz portion',
    price1: 0.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 7,
    category: 'SideOrder',
    name: 'Italian Dressing',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: '4oz portion',
    price1: 0.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 8,
    category: 'SideOrder',
    name: 'Caesar Dressing',
    description: null,
    images: '/images/icons-logos/buonos-logo-default.webp',
    size1: '4oz portion',
    price1: 0.75,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 9,
    category: 'SideOrder',
    name: 'Mikes Hot Honey',
    description: 'Infused with chilies.',
    images: '/images/menu-items/ny-favorite/mikes-hot-honey.webp',
    size1: '12 oz',
    price1: 10.00,
    size2: null,
    price2: null,
    size3: null,
    price3: null,
    isPasta: false
  },
  {
    id: 10,
    category: 'SideOrder',
    name: 'Polly-O Ricotta Cheese',
    description: 'Premium Italian natural ricotta cheese. A New York favorite.',
    images: '/images/menu-items/ny-favorite/polly-o-ricotta.webp',
    size1: '5 lb',
    price1: 17.99,
    size2: null,
    price2: null,
    size3: null,
    price3: null
  },
];